((emacs-lisp-mode . ((fill-column . 80)
                     (indent-tabs-mode . nil)
                     (sentence-end-double-space . t)
                     (eval . (put 'if-let* 'lisp-indent-function 1))
                     (eval . (put 'if-let 'lisp-indent-function 1))
                     (elisp-lint-indent-specs . ((if-let* . 1)
                                                 (if-let . 1)
                                                 (mcp-server-lib-test--with-server . 0)
                                                 (mcp-server-lib-test--with-tools . 1)
                                                 (mcp-server-lib-test--register-tool . 1)
                                                 (mcp-server-lib-test--with-resources . 1)
                                                 (mcp-server-lib-test--register-resource . 2)
                                                 (mcp-server-lib-test--register-resource-template . 2)
                                                 (mcp-server-lib-test--with-resource-templates . 1)
                                                 (mcp-server-lib-test--with-undefined-function . 1)
                                                 (mcp-server-lib-test--with-request . defun)
                                                 (mcp-server-lib-test--with-error-tracking . 1)
                                                 (mcp-server-lib-test--check-resource-read-error . 0)
                                                 (mcp-server-lib-ert-with-metrics-tracking . 1)
                                                 (mcp-server-lib-ert-verify-req-success . defun)
                                                 (cl-defstruct . nil)))))))